FROM python:3.13-slim

WORKDIR /app

RUN apt-get update && apt-get upgrade

COPY requirements.txt .

RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["uvicorn", "agent_server:app", "--host", "0.0.0.0", "--port", "8000"]