version: '3.9'

services:
  agent-server:
    build:
      context: ./agent-server
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    restart: unless-stopped

  adaptive-agent:
    build:
      context: .
      dockerfile: dockerfile
    command: ["python", "agent.py", "dev"]
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - agent-server
